# Site settings
title: 'Tylor Mayfield'
description: 'Business Card Page'
url: 'https://tsohg.com'
profilepic: '/images/TylorMayfield.png'
bkimage: '/images/12322820_10208140961391237_6106166124565719117_o.jpg'
author:
  name: 'Tylor Mayfield'
  email: 'tylor@tsohg.com'
  twitter_username: 'ghostbackwards'
  github_username: 'tylormayfield'
  linkedin_username: 'tylor-mayfield-a5991b78'
  strava: 'https://www.strava.com/athletes/52174287'

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
